environments:
  test: 
    base_url: "http://{PUBLIC_DOMAIN}"
    timeout: 30
    verify: false
    redis:
      host: "{REDIS_HOST}"
      port: 6379
      password: "{REDIS_PASSWORD}"
      db: 0

  uat:
    base_url: "https://{PUBLIC_DOMAIN}"
    timeout: 30
    verify: true
    redis:
      host: "{REDIS_HOST}"
      port: 6379
      password: "{REDIS_PASSWORD}"
      db: 0
    